name: water_reminder_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-213.0.dev <4.0.0'

dependencies:
  bloc: ^8.1.2
  circular_chart_flutter: ^0.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  font_awesome_flutter: ^10.5.0
  numberpicker: ^2.1.2
  shared_preferences: ^2.2.0
  sleek_circular_slider: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assests/water_reminder_app_photo/
    - assests/app_primary_photo/



flutter_launcher_icons:
  image_path: "assests/app_primary_photo/app_primary_photo.png"
  image_path_android: "assests/app_primary_photo/app_primary_photo.png"
  image_path_ios: "assests/app_primary_photo/app_primary_photo.png"
  
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
 # adaptive_icon_background: "assets/images/christmas-background.png" # only available for Android 8.0 devices and above
 # adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above
 # min_sdk_android: 21 # android min sdk min:16, default 21
 # remove_alpha_ios: true
 # background_color_ios: "#ffffff"